---

- name: verify whether java path exists
  shell: ls -al /etc/alternatives/javac
  register: javastatus
  tags: java
 
- name: ensure required packages are installed for Java 7
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-software-properties
  when: javastatus|failed
  tags: java
 
- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java'
  when: javastatus|failed
  tags: java
 
- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when: javastatus|failed
  tags: java
 
- name: Update APT package
  shell: sudo apt-get update 
  when: javastatus|failed
  tags: java
 
- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
  when: javastatus|failed
  tags: java
 
- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes
  when: javastatus|failed
  tags: java
